# Generated by Django 4.1.7 on 2023-04-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=97)),
                ('gender', models.CharField(max_length=6)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('image_jobs', models.ManyToManyField(blank=True, to='image.imagejob')),
                ('text_jobs', models.ManyToManyField(blank=True, to='text.textjob')),
            ],
        ),
    ]
